---
- hosts: webservers
  sudo: true

  vars:
    - db_name: drupal
    - db_user: drupal_user
    - db_password: drupaldbpass

    - web_root: /docroot/

  roles:
    - update
    - apache
    - php
    - drush
    - pecl
    - mysql


